quarkus:
  http:
    port: 8080
  log:
    level: INFO
  application:
    name: connecting-worlds

app:
  chatbots:
    - name: dotnet-chatbot
      url: http://dotnet-chatbot:8080/chat?message=
    - name: fastify-chatbot
      url: http://fastify-chatbot:3000/chat?message=